---
title: "Fundación Aru 2021"
date: "Enero, 2021"
output:
  rmdformats::robobook:
    highlight: kate
    number_sections: true
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Objetivos 2021-2022

  * Redes
    + Seguidores Facebook 4000 a 6000
    + Seguidores Twitter 600 a 900
  * Investigación
    + Repec
    + Google schoolar
  * Datos
    + Datum

# Instituyentes y proyectos 

## Política de overhead

## Política de asignación del personal

## Política de saldos de proyecto

# Estructura de Aru

## Director de investigación

## 

# Protocolos

## Herramientas de seguimiento

## Enlaces de interés

# Redes

## TTCSP

# Unidad de Administración

## Rastreo de Grands y proyectos

## Definición de cargos (promoción)

## Imagen institucional interna

# Estrategia de comunicación

## Radio Aru

## Página Web

## Políticas de puertas abiertas

# Unidad de Investigación

## Agendas de investigación

## Incentivos a la investigación

## Iniciativas

# Unidad de Microdatos

## Metadatos

## Iniciativas

# Gestión del conocimiento 

## Cursos de capacitación

## Cursos a demanda